[
  {
    "Name": "Cannabis Entity Prequalification Application",
    "Record Type": "Cannabis/Entity/Prequalification/Application",
    "Description": "Entity Prequalification form that is used to start the process of registration for a business entity. This record will generate all remaining applications for Businesses, Individuals, and Employees for registration.",
    "Status": "Review",
    "Record ID Mask": "MJ_Entity Prequalification App",
    "Workflow": "MJ_EPRE_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_EPRE_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_EPRE",
    "Pageflow": "MJ_Entity Prequalification",
    "Fee Schedule": "MJ_EPRE_APP",
    "Inspection Group": "NA",
    "Document Group": "MJ_EPRE_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Business Registration",
    "Record Type": "Cannabis/Entity/Registration/Business",
    "Description": "Business Registration for businesses involved in a Cannabis Business",
    "Status": "Review",
    "Record ID Mask": "MJ_Entity Registration",
    "Workflow": "MJ_ENTR",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_ENTR",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_ENTR",
    "Pageflow": "MJ_Entity Application",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_ENTR",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Employee Registration",
    "Record Type": "Cannabis/Entity/Registration/Employee",
    "Description": "Employee Registration for people involved in a Cannabis Business",
    "Status": "Review",
    "Record ID Mask": "MJ_Employee Registration",
    "Workflow": "MJ_EMPR",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_EMPR",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_EMPR",
    "Pageflow": "MJ_Employee Registration",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_IPRE_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Individual Registration",
    "Record Type": "Cannabis/Entity/Registration/Individual",
    "Description": "Individual Registration for people involved in a Cannabis Business",
    "Status": "Review",
    "Record ID Mask": "MJ_Individual Registration",
    "Workflow": "MJ_INDR",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_INDR",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_IPRE",
    "Pageflow": "MJ_Individual App",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_IPRE_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Cultivation Application",
    "Record Type": "Cannabis/Adult-Use/Cultivation/Application",
    "Description": "An entity licensed exclusively to cultivate, process, and package adult-use cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Cultivation App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUCUL_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUCUL",
    "Pageflow": "MJ_AU_Cultivation App",
    "Fee Schedule": "MJ_AUCOL_APP",
    "Inspection Group": "MJ_AUPR",
    "Document Group": "MJ_AUCUL_APP",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Cultivation License",
    "Record Type": "Cannabis/Adult-Use/Cultivation/License",
    "Description": "An entity licensed exclusively to cultivate, process, and package adult-use cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Cultivation Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUCUL_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUCUL",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Cultivation Renewal",
    "Record Type": "Cannabis/Adult-Use/Cultivation/Renewal",
    "Description": "An entity licensed exclusively to cultivate, process, and package adult-use cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Cultivation Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUCUL_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUCUL_REN",
    "Pageflow": "MJ_AU_Cultivation Ren",
    "Fee Schedule": "MJ_AUCOL_REN",
    "Inspection Group": "MJ_AUPR",
    "Document Group": "MJ_AUCUL_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Dispensary Application",
    "Record Type": "Cannabis/Adult-Use/Dispensary/Application",
    "Description": "Facility from which any individual twenty-one years of age or older may purchase adult-use cannabis. Adult-Use Cannabis may not be cultivated or processed under this license.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Dispensary App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUDIS_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUDIS",
    "Pageflow": "MJ_Dispensary App",
    "Fee Schedule": "MJ_AUDIS_APP",
    "Inspection Group": "MJ_AUDIS",
    "Document Group": "MJ_AUDIS_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Dispensary License",
    "Record Type": "Cannabis/Adult-Use/Dispensary/License",
    "Description": "Facility from which any individual twenty-one years of age or older may purchase adult-use cannabis. Adult-Use Cannabis may not be cultivated or processed under this license.",
    "Status": "Review",
    "Record ID Mask": "MJ_Dispensary Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUDIS_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUDIS",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_AUDIS_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Dispensary Renewal",
    "Record Type": "Cannabis/Adult-Use/Dispensary/Renewal",
    "Description": "Facility from which any individual twenty-one years of age or older may purchase adult-use cannabis. Adult-Use Cannabis may not be cultivated or processed under this license.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Dispensary Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUDIS_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUDIS_REN",
    "Pageflow": "MJ_Dispensary Ren",
    "Fee Schedule": "MJ_DIS_REN",
    "Inspection Group": "MJ_AUDIS",
    "Document Group": "MJ_AUDIS_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Optional Premises Cultivation Application",
    "Record Type": "Cannabis/Adult-Use/Optional Prem Culti/Application",
    "Description": "An Optional Premises Cultivation Operation and a Adult-Use Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Optional Prem Cult App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUOP_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUOP",
    "Pageflow": "MJ_AU OptP Cultivation App",
    "Fee Schedule": "MJ_AUOP_APP",
    "Inspection Group": "MJ_AUOP",
    "Document Group": "MJ_AUOP_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Optional Premises Cultivation License",
    "Record Type": "Cannabis/Adult-Use/Optional Prem Culti/License",
    "Description": "An Optional Premises Cultivation Operation and a Adult-Use Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Optional Prem Cult Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUOP_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUOP",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_AUOP",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Optional Premises Cultivation Renewal",
    "Record Type": "Cannabis/Adult-Use/Optional Prem Culti/Renewal",
    "Description": "An Optional Premises Cultivation Operation and a Adult-Use Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Optional Prem Cult Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUOP_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUOP_REN",
    "Pageflow": "MJ_AU OptP Cultivation Ren",
    "Fee Schedule": "MJ_AUOP_REN",
    "Inspection Group": "MJ_AUOP",
    "Document Group": "MJ_AUOP_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Processor Application",
    "Record Type": "Cannabis/Adult-Use/Processor/Application",
    "Description": "An entity that processes, packages, and labels usable cannabis products exclusively for adult-use.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Processor App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUPR_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUPR",
    "Pageflow": "MJ_AU_Processor App",
    "Fee Schedule": "MJ_AUPR_APP",
    "Inspection Group": "MJ_AUPR_APP",
    "Document Group": "MJ_AUPR_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Processor License",
    "Record Type": "Cannabis/Adult-Use/Processor/License",
    "Description": "An entity that processes, packages, and labels usable cannabis products exclusively for adult-use.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Processor Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUPR_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUPR",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_AUPR_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Processor Renewal",
    "Record Type": "Cannabis/Adult-Use/Processor/Renewal",
    "Description": "An entity that processes, packages, and labels usable cannabis products exclusively for adult-use.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Processor Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUPR_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUPR_REN",
    "Pageflow": "MJ_AU_Processor Ren",
    "Fee Schedule": "MJ_AUPR_REN",
    "Inspection Group": "MJ_AUPR",
    "Document Group": "MJ_AUPR_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Product Manufacturer Application",
    "Record Type": "Cannabis/Adult-Use/Manufacturer/Application",
    "Description": "An entity licensed to obtain, manufacture, process and package adult-use cannabis and cannabis concentrates and infused products, to deliver cannabis and cannabis products to cannabis establishments and to transfer cannabis and cannabis products to other cannabis establishments, but not to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Product MFR App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUMFR_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUMFR",
    "Pageflow": "MJ_AU_Prod MFG App",
    "Fee Schedule": "MJ_AUMFR_APP",
    "Inspection Group": "MJ_AUMFR",
    "Document Group": "MJ_AUMFR_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Product Manufacturer License",
    "Record Type": "Cannabis/Adult-Use/Manufacturer/License",
    "Description": "An entity licensed to obtain, manufacture, process and package adult-use cannabis and cannabis concentrates and infused products, to deliver cannabis and cannabis products to cannabis establishments and to transfer cannabis and cannabis products to other cannabis establishments, but not to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Product MFR Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUMFR_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUMFR",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_AUMFR_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Product Manufacturer Renewal",
    "Record Type": "Cannabis/Adult-Use/Manufacturer/Renewal",
    "Description": "An entity licensed to obtain, manufacture, process and package adult-use cannabis and cannabis concentrates and infused products, to deliver cannabis and cannabis products to cannabis establishments and to transfer cannabis and cannabis products to other cannabis establishments, but not to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Product MFR Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUMFR_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUMFR_REN",
    "Pageflow": "MJ_AU_Prod MFG Ren",
    "Fee Schedule": "MJ_AUMFR_REN",
    "Inspection Group": "MJ_AUMFR",
    "Document Group": "MJ_AUMFR_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Transport Application",
    "Record Type": "Cannabis/Adult-Use/Transport/Application",
    "Description": "Allows entity to transport adult-use cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Transport App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUTR_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUTR",
    "Pageflow": "MJ_AU_Transport App",
    "Fee Schedule": "MJ_AUTR_APP",
    "Inspection Group": "MJ_TRANSPORT",
    "Document Group": "MJ_AUTR_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Transport License",
    "Record Type": "Cannabis/Adult-Use/Transport/License",
    "Description": "Allows entity to transport adult-use cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Transport Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUTR_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUTR",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_AUTR_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Adult-Use Cannabis Transport Renewal",
    "Record Type": "Cannabis/Adult-Use/Transport/Renewal",
    "Description": "Allows entity to transport adult-use cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed.",
    "Status": "Review",
    "Record ID Mask": "MJ_Adult-Use Transport Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_AUTR_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_AUTR_REN",
    "Pageflow": "MJ_AU_Transport Ren",
    "Fee Schedule": "MJ_AUTR_REN",
    "Inspection Group": "MJ_TRANSPORT",
    "Document Group": "MJ_AUTR_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Medical Center Application",
    "Record Type": "Cannabis/Medical/Medical Center/Application",
    "Description": "A not-for-profit entity, that acquires, cultivates, possesses, processes, transfers, transports, sells, distributes, dispenses, or administers cannabis, products containing cannabis, related supplies, or educational materials to qualifying patients or their personal caregivers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Center App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDC_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDC",
    "Pageflow": "MJ_Medical Center App",
    "Fee Schedule": "MJ_MDC_APP",
    "Inspection Group": "MJ_RTS",
    "Document Group": "MJ_MDC_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Medical Center License",
    "Record Type": "Cannabis/Medical/Medical Center/License",
    "Description": "A not-for-profit entity, that acquires, cultivates, possesses, processes, transfers, transports, sells, distributes, dispenses, or administers cannabis, products containing cannabis, related supplies, or educational materials to qualifying patients or their personal caregivers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Center Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDC_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDC",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_MDC_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Medical Center Renewal",
    "Record Type": "Cannabis/Medical/Medical Center/Renewal",
    "Description": "A not-for-profit entity, that acquires, cultivates, possesses, processes, transfers, transports, sells, distributes, dispenses, or administers cannabis, products containing cannabis, related supplies, or educational materials to qualifying patients or their personal caregivers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Center Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDC_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDC_REN",
    "Pageflow": "MJ_Medical Center Ren",
    "Fee Schedule": "MJ_MDC_REN",
    "Inspection Group": "MJ_RTS",
    "Document Group": "MJ_MDC_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Microbusiness Application",
    "Record Type": "Cannabis/Combo/Microbusiness/Application",
    "Description": "The license allows small businesses to act as a one-stop-shop; owners could grow cannabis on an area of less than 10,000 square feet, while also acting as distributor, non-volatile manufacturer and retailer.",
    "Status": "Review",
    "Record ID Mask": "MJ_Microbusiness App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COMB_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COMB",
    "Pageflow": "MJ_Microbusiness App",
    "Fee Schedule": "MJ_COMB_APP",
    "Inspection Group": "",
    "Document Group": "MJ_COMB_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Microbusiness License",
    "Record Type": "Cannabis/Combo/Microbusiness/License",
    "Description": "The license would allow small Businesses to act as a one-stop-shop; owners could grow cannabis on an area of less than 10,000 square feet, while also acting as distributor, non-volatile manufacturer and retailer.",
    "Status": "Review",
    "Record ID Mask": "MJ_Microbusiness Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COMB_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COMB",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_COMB_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Microbusiness Renewal",
    "Record Type": "Cannabis/Combo/Microbusiness/Renewal",
    "Description": "The license would allow small businesses to act as a one-stop-shop; owners could grow cannabis on an area of less than 10,000 square feet, while also acting as distributor, non-volatile manufacturer and retailer.",
    "Status": "Review",
    "Record ID Mask": "MJ_Microbusiness Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COMB_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COMB_REN",
    "Pageflow": "MJ_Microbusiness Ren",
    "Fee Schedule": "MJ_COMB_REN",
    "Inspection Group": "",
    "Document Group": "MJ_COMB_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Testing Facility Application",
    "Record Type": "Cannabis/Combo/Testing Facility/Application",
    "Description": "A laboratory that is licensed and is:(i) accredited, (ii) independent financially from any medical cannabis treatment center or any licensee or cannabis establishment for which it conducts a test; and (iii) qualified to test cannabis in compliance with regulations promulgated by the commission pursuant to this chapter.",
    "Status": "Review",
    "Record ID Mask": "MJ_Testing Facility App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COT_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COT",
    "Pageflow": "MJ_Test Facility App",
    "Fee Schedule": "MJ_COTF_APP",
    "Inspection Group": "MJ_COTF",
    "Document Group": "MJ_COT_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Testing Facility License",
    "Record Type": "Cannabis/Combo/Testing Facility/License",
    "Description": "A laboratory that is licensed and is:(i) accredited, (ii) independent financially from any medical cannabis treatment center or any licensee or cannabis establishment for which it conducts a test; and (iii) qualified to test cannabis in compliance with regulations promulgated by the commission pursuant to this chapter.",
    "Status": "Review",
    "Record ID Mask": "MJ_Testing Facility Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COT_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COT",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_COT_APP",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Testing Facility Renewal",
    "Record Type": "Cannabis/Combo/Testing Facility/Renewal",
    "Description": "A laboratory that is licensed and is:(i) accredited, (ii) independent financially from any medical cannabis treatment center or any licensee or cannabis establishment for which it conducts a test; and (iii) qualified to test cannabis in compliance with regulations promulgated by the commission pursuant to this chapter.",
    "Status": "Review",
    "Record ID Mask": "MJ_Testing Facility Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COT_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COT_REN",
    "Pageflow": "MJ_Test Facility Ren",
    "Fee Schedule": "MJ_COTF_REN",
    "Inspection Group": "MJ_COTF",
    "Document Group": "MJ_COT_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Cultivation Application",
    "Record Type": "Cannabis/Combo/Cultivation/Application",
    "Description": "An entity licensed to cultivate, process, and package medical AND adult-use cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers license allows for the cultivation and harvesting of Adult-Use and Medical cannabis plants.",
    "Status": "Review",
    "Record ID Mask": "MJ_Cultivation App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_CL_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_CCL",
    "Pageflow": "MJ_Cultivation App",
    "Fee Schedule": "MJ_COCL_APP",
    "Inspection Group": "MJ_COOP",
    "Document Group": "MJ_CCL_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Cultivation License",
    "Record Type": "Cannabis/Combo/Cultivation/License",
    "Description": "An entity licensed to cultivate, process, and package medical AND adult-use cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers license allows for the cultivation and harvesting of Adult-Use and Medical cannabis plants.",
    "Status": "Review",
    "Record ID Mask": "MJ_Cultivation Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_CL_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_CCL",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_CCL",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Cultivation Renewal",
    "Record Type": "Cannabis/Combo/Cultivation/Renewal",
    "Description": "An entity licensed to cultivate, process, and package medical AND adult-use cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers license allows for the cultivation and harvesting of Adult-Use and Medical cannabis plants.",
    "Status": "Review",
    "Record ID Mask": "MJ_Cultivation Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_CL_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_CCL_REN",
    "Pageflow": "MJ_Cultivation Ren",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Dispensary Application",
    "Record Type": "Cannabis/Combo/Dispensary/Application",
    "Description": "Facility from which Adult-Use and Medical Cannabis Registry patients purchase Cannabis and Cannabis infused products.",
    "Status": "Review",
    "Record ID Mask": "MJ_Dispensary App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COD_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COD",
    "Pageflow": "MJ_Dispensary App",
    "Fee Schedule": "MJ_COD_APP",
    "Inspection Group": "MJ_RTS",
    "Document Group": "MJ_COD_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Dispensary License",
    "Record Type": "Cannabis/Combo/Dispensary/License",
    "Description": "Facility from which Adult-Use and Medical Cannabis Registry patients purchase Cannabis and Cannabis infused products.",
    "Status": "Review",
    "Record ID Mask": "MJ_Dispensary Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COD_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COD",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_COD_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Dispensary Renewal",
    "Record Type": "Cannabis/Combo/Dispensary/Renewal",
    "Description": "Facility from which Adult-Use and Medical Cannabis Registry patients purchase Cannabis and Cannabis infused products.",
    "Status": "Review",
    "Record ID Mask": "MJ_Dispensary Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COD_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COD_REN",
    "Pageflow": "MJ_Dispensary Ren",
    "Fee Schedule": "MJ_COD_REN",
    "Inspection Group": "MJ_RTS",
    "Document Group": "MJ_COD_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Optional Premises Cultivation Application",
    "Record Type": "Cannabis/Combo/Optional Prem Culti/Application",
    "Description": "An Optional Premises Cultivation Operation and a Adult-Use Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_Optional Premises Cultivation App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COOP_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COOP",
    "Pageflow": "MJ_OptP Cultivation App",
    "Fee Schedule": "MJ_COOP_APP",
    "Inspection Group": "MJ_COOP",
    "Document Group": "MJ_COOP_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Optional Premises Cultivation License",
    "Record Type": "Cannabis/Combo/Optional Prem Culti/License",
    "Description": "An Optional Premises Cultivation Operation and a Adult-Use Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_AU Optional Premises Cultivation Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COOP_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COOP",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_COOP",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Optional Premises Cultivation Renewal",
    "Record Type": "Cannabis/Combo/Optional Prem Culti/Renewal",
    "Description": "An Optional Premises Cultivation Operation and a Adult-Use Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_Optional Premises Cultivation Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_COOP_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_COOP_REN",
    "Pageflow": "MJ_OptP Cultivation Ren",
    "Fee Schedule": "MJ_COOP_REN",
    "Inspection Group": "MJ_COOP",
    "Document Group": "MJ_COOP_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Processor Application",
    "Record Type": "Cannabis/Combo/Processor/Application",
    "Description": "An entity that processes, packages, and labels usable cannabis products for sale at wholesale to cannabis retailers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Processor App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_PR_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_PR",
    "Pageflow": "MJ_Processor App",
    "Fee Schedule": "MJ_COPR_APP",
    "Inspection Group": "",
    "Document Group": "MJ_PR_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Processor License",
    "Record Type": "Cannabis/Combo/Processor/License",
    "Description": "An entity that processes, packages, and labels usable cannabis products for sale at wholesale to cannabis retailers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Processor Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_PR_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_PR",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_PR_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Processor Renewal",
    "Record Type": "Cannabis/Combo/Processor/Renewal",
    "Description": "An entity that processes, packages, and labels usable cannabis products for sale at wholesale to cannabis retailers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Processor Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_PR_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_PR_REN",
    "Pageflow": "MJ_Processor Ren",
    "Fee Schedule": "MJ_COPR_REN",
    "Inspection Group": "MJ_AUDIS",
    "Document Group": "MJ_PR_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Transport Application",
    "Record Type": "Cannabis/Combo/Secure Transporter/Application",
    "Description": "Allows companies to transport adult-use and medical cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed",
    "Status": "Review",
    "Record ID Mask": "MJ_Secure Transporter App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_STR_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_STR",
    "Pageflow": "MJ_Secure Transporter App",
    "Fee Schedule": "MJ_STR_APP",
    "Inspection Group": "MJ_TRANSPORT",
    "Document Group": "MJ_STR_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Transport License",
    "Record Type": "Cannabis/Combo/Secure Transporter/License",
    "Description": "Allows companies to transport adult-use and medical cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed",
    "Status": "Review",
    "Record ID Mask": "MJ_Secure Transporter Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_STR_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_STR",
    "Pageflow": "",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_STR_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Combo Cannabis Transport Renewal",
    "Record Type": "Cannabis/Combo/Secure Transporter/Renewal",
    "Description": "Allows companies to transport adult-use and medical cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed",
    "Status": "Review",
    "Record ID Mask": "MJ_Secure Transporter Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_STR_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_STR_REN",
    "Pageflow": "MJ_Secure Transporter Ren",
    "Fee Schedule": "MJ_STR_REN",
    "Inspection Group": "",
    "Document Group": "MJ_STR_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Cultivation Application",
    "Record Type": "Cannabis/Medical/Cultivation/Application",
    "Description": "An entity licensed exclusively to cultivate, process, and package medical cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Cultivation App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDCUL_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDCUL",
    "Pageflow": "MJ_Cultivation App",
    "Fee Schedule": "MJ_MDCUL_APP",
    "Inspection Group": "MJ_MDP",
    "Document Group": "MJ_MDCUL_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Cultivation License",
    "Record Type": "Cannabis/Medical/Cultivation/License",
    "Description": "An entity licensed exclusively to cultivate, process, and package medical cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Cultivation Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDCUL_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDCUL",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_MDCUL",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Cultivation Renewal",
    "Record Type": "Cannabis/Medical/Cultivation/Renewal",
    "Description": "An entity licensed exclusively to cultivate, process, and package medical cannabis, to deliver cannabis to cannabis establishments, but NOT to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Cultivation Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDCUL_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDCUL_REN",
    "Pageflow": "MJ_AU_Cultivation Ren",
    "Fee Schedule": "MJ_MDCUL_REN",
    "Inspection Group": "MJ_MDP",
    "Document Group": "MJ_MDCUL",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Dispensary Application",
    "Record Type": "Cannabis/Medical/Dispensary/Application",
    "Description": "Facility from which Medical Cannabis Registry patients purchase Medical Cannabis and Medical Cannabis infused products.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Dispensary App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDDIS_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDDIS",
    "Pageflow": "MJ_Dispensary App",
    "Fee Schedule": "MJ_MDDIS_APP",
    "Inspection Group": "MJ_MDDIS",
    "Document Group": "MJ_MDDIS_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Dispensary License",
    "Record Type": "Cannabis/Medical/Dispensary/License",
    "Description": "Facility from which Medical Cannabis Registry patients purchase Medical Cannabis and Medical Cannabis infused products.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Dispensary Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDDIS_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDDIS",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_MDDIS_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Dispensary Renewal",
    "Record Type": "Cannabis/Medical/Dispensary/Renewal",
    "Description": "Facility from which Medical Cannabis Registry patients purchase Medical Cannabis and Medical Cannabis infused products.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Dispensary Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDDIS_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDDIS_REN",
    "Pageflow": "MJ_Dispensary Ren",
    "Fee Schedule": "MJ_MDDIS_REN",
    "Inspection Group": "MJ_MDDIS",
    "Document Group": "MJ_MDDIS_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Optional Premises Cultivation Application",
    "Record Type": "Cannabis/Medical/Optional Prem Culti/Application",
    "Description": "An Optional Premises Cultivation Operation and a medical Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Optional Prem Cult App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDOP_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDOP",
    "Pageflow": "MJ_OptP Cultivation App",
    "Fee Schedule": "MJ_MDOP_APP",
    "Inspection Group": "MJ_MDP",
    "Document Group": "MJ_MDOP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Optional Premises Cultivation License",
    "Record Type": "Cannabis/Medical/Optional Prem Culti/License",
    "Description": "An Optional Premises Cultivation Operation and a medical Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Optional Prem Cult Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDOP_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDOP",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_MDOP",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Optional Premises Cultivation Renewal",
    "Record Type": "Cannabis/Medical/Optional Prem Culti/Renewal",
    "Description": "An Optional Premises Cultivation Operation and a medical Cannabis Cultivation Facility may share a single Licensed Premises in order to operate a dual cultivation business operation if the relevant local jurisdiction permits a dual operation at the same location and the two are commonly owned.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Optional Prem Cult Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDOP_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDOP_REN",
    "Pageflow": "MJ_OptP Cultivation Ren",
    "Fee Schedule": "MJ_MDOP_REN",
    "Inspection Group": "MJ_MDP",
    "Document Group": "MJ_MDOP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Processor Application",
    "Record Type": "Cannabis/Medical/Processor/Application",
    "Description": "An entity that processes, packages, and labels usable medical cannabis products for sale at wholesale to cannabis medical facilities",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Processor App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDPR_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDPR",
    "Pageflow": "MJ_MD_Processor App",
    "Fee Schedule": "MJ_MDPR_APP",
    "Inspection Group": "MJ_MDPR_APP",
    "Document Group": "MJ_MDPR_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Processor License",
    "Record Type": "Cannabis/Medical/Processor/License",
    "Description": "An entity that processes, packages, and labels usable medical cannabis products for sale at wholesale to cannabis medical facilities",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Processor Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDPR_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDPR",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_MDPR_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Processor Renewal",
    "Record Type": "Cannabis/Medical/Processor/Renewal",
    "Description": "An entity that processes, packages, and labels usable medical cannabis products for sale at wholesale to cannabis medical facilities",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Processor Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDPR_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDPR_REN",
    "Pageflow": "MJ_MD_Processor Ren",
    "Fee Schedule": "MJ_MDPR_REN",
    "Inspection Group": "MJ_MDPR",
    "Document Group": "MJ_MDPR_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Product Manufacturer Application",
    "Record Type": "Cannabis/Medical/Manufacturer/Application",
    "Description": "An entity licensed to obtain, manufacture, process and package medical cannabis and cannabis concentrates and infused products, to deliver cannabis and cannabis products to cannabis establishments and to transfer cannabis and cannabis products to other cannabis establishments, but not to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Product MFR App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDMFR_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDMFR",
    "Pageflow": "MJ_MD_Prod MFG App",
    "Fee Schedule": "MJ_MDMFR_APP",
    "Inspection Group": "MJ_MDP",
    "Document Group": "MJ_MDMFR_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Product Manufacturer License",
    "Record Type": "Cannabis/Medical/Manufacturer/License",
    "Description": "An entity licensed to obtain, manufacture, process and package medical cannabis and cannabis concentrates and infused products, to deliver cannabis and cannabis products to cannabis establishments and to transfer cannabis and cannabis products to other cannabis establishments, but not to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Product MFR Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDMFR_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDMFR",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_MDMFR_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Product Manufacturer Renewal",
    "Record Type": "Cannabis/Medical/Manufacturer/Renewal",
    "Description": "An entity licensed to obtain, manufacture, process and package medical cannabis and cannabis concentrates and infused products, to deliver cannabis and cannabis products to cannabis establishments and to transfer cannabis and cannabis products to other cannabis establishments, but not to consumers.",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Product MFR Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDMFR_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDMFR_REN",
    "Pageflow": "MJ_MD_Prod MFG Ren",
    "Fee Schedule": "MJ_MDMFR_REN",
    "Inspection Group": "MJ_MDP",
    "Document Group": "MJ_MDMFR_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Transport Application",
    "Record Type": "Cannabis/Medical/Transport/Application",
    "Description": "Allows companies to transport medical cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Transport App",
    "Workflow": "MJ_APP",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDTR_APP",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDTR",
    "Pageflow": "MJ_MD_Transport App",
    "Fee Schedule": "MJ_MDTR_APP",
    "Inspection Group": "MJ_TRANSPORT",
    "Document Group": "MJ_MDTR_APP",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Transport License",
    "Record Type": "Cannabis/Medical/Transport/License",
    "Description": "Allows companies to transport medical cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Transport Lic",
    "Workflow": "MJ_LICENSE",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDTR_LIC",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDTR",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "MJ_MDTR_LIC",
    "Expiration Code": "MJ_GENERAL",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Medical Cannabis Transport Renewal",
    "Record Type": "Cannabis/Medical/Transport/Renewal",
    "Description": "Allows companies to transport medical cannabis products between licensed facilities or customers, as well as to temporarily store the product in a designated location if needed",
    "Status": "Review",
    "Record ID Mask": "MJ_Medical Transport Ren",
    "Workflow": "MJ_RENEW",
    "Status Group": "MJ_STATUS",
    "Custom Field Group": "MJ_MDTR_REN",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_MDTR_REN",
    "Pageflow": "MJ_MD_Transport Ren",
    "Fee Schedule": "MJ_MDTR_REN",
    "Inspection Group": "MJ_TRANSPORT",
    "Document Group": "MJ_MDTR_REN",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Enforcement Audit",
    "Record Type": "Cannabis/Enforcement/Audit/NA",
    "Description": "Allows agency to audit a subset of records scheduled or as needed.",
    "Status": "Confirmed",
    "Record ID Mask": "MJ_License Audit",
    "Workflow": "MJ_AUDIT",
    "Status Group": "ENF_COMPLAINT",
    "Custom Field Group": "MJ_LIC_AUDIT",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_LIC_AUDIT",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "NA",
    "Document Group": "SS_AUDIT",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Enforcement Case",
    "Record Type": "Cannabis/Enforcement/Case/NA",
    "Description": "Allows agency to create and track enforcement cases",
    "Status": "Confirmed",
    "Record ID Mask": "MJ_Enforcement Case",
    "Workflow": "MJ_ENF_CASE",
    "Status Group": "MJ_Enforcement",
    "Custom Field Group": "MJ_ENF_CASE",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_ENF_CASE",
    "Pageflow": "NA",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_ENF_CASE",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Enforcement Complaint",
    "Record Type": "Cannabis/Enforcement/Complaint/NA",
    "Description": "Allows public to submit complaints against a cannabis business or affiliated individual.",
    "Status": "Confirmed",
    "Record ID Mask": "MJ_Complaint",
    "Workflow": "MJ_ENF_COMPLAINT",
    "Status Group": "MJ_Enforcement",
    "Custom Field Group": "MJ_COMPLAINT",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_ENF_COMPLAINT",
    "Pageflow": "MJ_Enforcement Complaint",
    "Fee Schedule": "NONE",
    "Inspection Group": "",
    "Document Group": "MJ_COMPLAINT",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis Enforcement Violation",
    "Record Type": "Cannabis/Enforcement/Violation/NA",
    "Description": "Allows agency to create and track violations related to cannabis business entities and individuals.",
    "Status": "Confirmed",
    "Record ID Mask": "MJ_Violation",
    "Workflow": "MJ_ENF_VIOLATION",
    "Status Group": "MJ_Enforcement",
    "Custom Field Group": "MJ_VIOLATION",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_ENF_CASE",
    "Pageflow": "NA",
    "Fee Schedule": "MJ_ENFORCEMENT",
    "Inspection Group": "",
    "Document Group": "MJ_ENF_CASE",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  },
  {
    "Name": "Cannabis License Modification",
    "Record Type": "Cannabis/Amendment/License Modification/NA",
    "Description": "This amendment form will allow modifications to be made to the license.",
    "Status": "Review",
    "Record ID Mask": "MJ_Amendment License Modification",
    "Workflow": "MJ_LIC_MODIFY",
    "Status Group": "MJ_AMEND",
    "Custom Field Group": "MJ_MODIFY",
    "Custom List": "",
    "Shared Dropdown": "",
    "Intake Form": "MJ_LIC_MODIFY",
    "Pageflow": "MJ_License Amendment",
    "Fee Schedule": "MJ LICENSE MOD",
    "Inspection Group": "NA",
    "Document Group": "Marijuana License Modification",
    "Expiration Code": "NONE",
    "Purchase Status": "",
    "Package Status": ""
  }
]